disabled_rules:
  - identifier_name


# Paths to exclude from linting
excluded:
  - .build
  - Tests
  - TestData

# Adjust specific rule settings
line_length: 140
type_body_length: 360
file_length: 550
